- Security/apps.sql
- dbo/Stored Procedures/GenerateTableFromView.sql
- dbo/Views/v_POM.sql
- dbo/Views/v_PoM_Codes.sql
> for 347928

- Security/apps.sql
- dbo/Stored Procedures/GenerateTableFromView.sql
- dbo/Views/v_POM.sql
- dbo/Views/v_PoM_Codes.sql
merging from feature branch to main
> For 384051

- Database.sqlproj
- Security/apps.sql
- dbo/Views/registration.sql
- dbo/Views/v_Multiple_Reg_Sumbissions.sql
- dbo/Views/v_POM.sql
- dbo/Views/v_registration_latest_by_Year.sql
- dbo/Views/v_registration_with_brandandpartner.sql
> for 372884, 361763 and 393882

- dbo/Views/v_POM_Extract_Fix.sql
- dbo/Views/v_registration_latest.sql
- dbo/Views/v_registration_latest_by_Year.sql
> for 292684

- dbo/Views/v_PoM_Codes.sql
- dbo/Views/v_registration_with_brandandpartner.sql
Bug fixes for 372884 & 403735 (#37)  as part of Release 4.0
> Bug fixes for 372884 & 403735 (#37)

- dbo/Views/v_Enrolmentstatus.sql
> for 402923

- dbo/Stored Procedures/POM_Comparison_ARROW_LOGIC.sql
- dbo/Stored Procedures/POM_Comparison_DRILL.sql
- dbo/Stored Procedures/POM_Comparison_members.sql
> 9cbcb7a7 on main

- Delta Lake Files/ctrl_table.csv
> update config file

- dbo/Views/v_Enrolmentstatus.sql
> Ticket 423018 (#64)

- dbo/Views/v_subsidiaryorganisations.sql
> 410948 Subsidiary Changes

- dbo/Views/v_subsidiaryorganisations.sql
> 410948 Subsidiary Changes (#68)

- dbo/Views/v_POM.sql
- dbo/Views/v_registration_with_brandandpartner.sql
- dbo/Views/v_subsidiaryorganisations_1.sql
- rpd/Tables/OrganisationRegistrationTypes.sql
- rpd/Tables/OrganisationRelationshipTypes.sql
- rpd/Tables/OrganisationRelationships.sql
- rpd/Tables/SubsidiaryOrganisations.sql
Ticket 410948 additional subsids
> Ticket 410948 additional subsids (#70)

- Delta Lake Files/ctrl_table.csv
The below tables has been added to ctrl file
1. OrganisationRelationshipTypes
2. OrganisationRelationships
3. OrganisationRegistrationTypes
4. SubsidiaryOrganisations
> Changes in Config file for R5.0

- Database.sqlproj
Following are done manually editing it outside visual studio. Directly opening the file in notepad++ from backend. Made sure that local repository HEAD is pointing to feature branch. This was done by selecting feature branch in VS professional.
renamed t_pom_codes_1.sql              to t_pom_codes.sql
renamed sp_delete_duplicate_rows_1.sql to sp_delete_duplicate_rows.sql
> Updated Database.sqlproj file. Renamed the 2 wrong entries with _1 prefix.

- Delta Lake Files/ctrl_table.csv
duplicate entries for the following  are removed.
PersonsConnections
InterPersonRoles
> Removed 2 duplicates entries from ctrl_table.csv

- Delta Lake Files/ctrl_table.csv
Removed duplicate entries for the following tables.  PersonsConnections
InterPersonRoles
> Removed the duplicate entries from ctrl_table.csv

- dbo/Stored Procedures/GenerateTableFromView.sql
tables are now put into right sequence.
> table sequences in sp corrected

- dbo/Stored Procedures/GenerateTableFromView.sql
tables are now put into right sequence.
> table sequences in sp corrected (#107)

- dbo/Views/v_Large_Producers.sql
- dbo/Views/v_extract_recent_pom_org_data.sql
ADO 448050
Desc:  Multiple_subsid_ids_in_PLLP_report#
> 448050_multiple_subsid_ids_in_PLLP_report

- Database.sqlproj
- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
- dbo/Views/v_CompanyBrandPartnerFileUploadSet.sql
- dbo/Views/v_Registration_Comparison_Landing_Page.sql
ADO: 473945, 475952
Desc: RegistrationComparisonReport
> 473945_475952_RegistrationComparisonReport

- Delta Lake Files/PRN_ctrl_table.csv
> Adding PRN config file

- dbo/Views/v_Large_Producers.sql
- dbo/Views/v_extract_recent_pom_org_data.sql
v_Large_Producers.sql
v_extract_recent_pom_org_data.sql
> PLLP changes for release 6.2

- dbo/Stored Procedures/sp_GetCsoMemberDetailsByOrganisationId.sql
- dbo/Stored Procedures/sp_GetProducerDetailsByOrganisationId.sql
> Producer Stored Proc changes

- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails.sql
- dbo/Stored Procedures/sp_FilterAndPaginateOrganisationRegistrationSummaries.sql
> Updated stored procs

- Database.sqlproj
- dbo/Stored Procedures/CrossValidation.sql
- dbo/Stored Procedures/CrossValidationGetLatestFile.sql
- dbo/Views/v_CrossValidation_FileDetails_Main.sql
- dbo/Views/v_CrossValidation_FileDetails_ORG.sql
- dbo/Views/v_CrossValidation_FileDetails_POM.sql
- dbo/Views/v_CrossValidation_FileDetails_Registration.sql
Cross Validation Landing page SQL
1. List of Views:
[dbo].[v_CrossValidation_FileDetails_Main]
[dbo].[v_CrossValidation_FileDetails_ORG]
[dbo].[v_CrossValidation_FileDetails_POM]
[dbo].[v_CrossValidation_FileDetails_Registration]
2. List of Stored precedure:
[dbo].[CrossValidation]
[dbo].[CrossValidationGetLatestFile]
> Cross Validation Landing Page SQLS

- Database.sqlproj
correction for the object list
> correction for the object list

- Database.sqlproj
- dbo/Stored Procedures/GenerateTableFromView.sql
- dbo/Stored Procedures/sp_compare_org_file.sql
- dbo/Tables/t_latest_accepted_orgfile_by_year.sql
- dbo/Tables/t_latest_pending_or_accepted_orgfile_by_year.sql
- dbo/Views/v_get_orgfile_submitted_year.sql
- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
487661 - Joiners and Leavers report - Create SQL stored procedure to identify joiners and leavers of a Compliance scheme
> 487661 - Joiners and Leavers report

- dbo/Views/v_New_Enrolment_Report.sql
> additional columns

- dbo/Views/v_New_Enrolment_Report.sql
> 462849-additional columns (#127)

- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails.sql
- dbo/Stored Procedures/sp_GetProducerDetailsByOrganisationId.sql
- dbo/Views/v_OrganisationRegistrationSummaries.sql
- dbo/Views/v_ProducerPaycalParameters.sql
- dbo/Views/v_UploadedRegistrationDataBySubmissionPeriod.sql
Cherry picking R7 08/Jan changes into R8 release branch
> Producer stored proc changes (#129) Cherry picking R7 08/Jan changes into R8 release branch

- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails.sql
- dbo/Stored Procedures/sp_GetProducerDetailsByOrganisationId.sql
- dbo/Views/v_OrganisationRegistrationSummaries.sql
- dbo/Views/v_ProducerPaycalParameters.sql
- dbo/Views/v_UploadedRegistrationDataBySubmissionPeriod.sql
b759c237_on_R9
Cherry picking R7 08/Jan changes into R9 release branch
> Producer stored proc changes (#129) Cherry picking R7 08/Jan changes into R9 release branch

- Database.sqlproj
- dbo/Stored Procedures/CrossValidation.sql
- dbo/Stored Procedures/CrossValidationGetLatestFile.sql
- dbo/Views/v_CrossValidation_FileDetails_Main.sql
- dbo/Views/v_CrossValidation_FileDetails_ORG.sql
- dbo/Views/v_CrossValidation_FileDetails_POM.sql
- dbo/Views/v_CrossValidation_FileDetails_Registration.sql
1. List of Views: [dbo].[v_CrossValidation_FileDetails_Main]
[dbo].[v_CrossValidation_FileDetails_ORG]
[dbo].[v_CrossValidation_FileDetails_POM]
[dbo].[v_CrossValidation_FileDetails_Registration]
2. List of Stored precedure: [dbo].[CrossValidation]
[dbo].[CrossValidationGetLatestFile]
Cherry picking R7 CV 30/Dec changes into R8 release branch
> Cross Validation Landing Page SQLS (#121)

- Database.sqlproj
Cherry picking R7 CV 30/Dec changes into R8 release branch
> correction for the object list (#123)

- Database.sqlproj
- dbo/Stored Procedures/CrossValidation.sql
- dbo/Stored Procedures/CrossValidationGetLatestFile.sql
- dbo/Stored Procedures/CrossValidation_Registration.sql
- dbo/Views/v_CrossValidation_FileDetails_Main.sql
- dbo/Views/v_CrossValidation_FileDetails_ORG.sql
- dbo/Views/v_CrossValidation_FileDetails_POM.sql
- dbo/Views/v_CrossValidation_POM_Data.sql
Adding new cross validation objects for ticket 412814 targeting for R9
dev : BO
> Adding new cross validation objects for ticket 412814 targeting for R9

- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails.sql
- dbo/Stored Procedures/sp_GetProducerDetailsByOrganisationId.sql
- dbo/Views/v_OrganisationRegistrationSummaries.sql
Latest producer changes for R7
> Latest producer changes for R7

- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails.sql
- dbo/Views/v_OrganisationRegistrationSummaries.sql
Latest producer journey changes for R7
> Latest producer changes for R7 (#140)

- dbo/Views/v_PRN_Details.sql
- dbo/Views/v_PRN_Obligations.sql
> PRN view changes for R7

- dbo/Views/v_PRN_Details.sql
- dbo/Views/v_PRN_Obligations.sql
> PRN view changes for R7 (#143)

- Database.sqlproj
- dbo/Stored Procedures/GenerateTableFromView.sql
- dbo/Tables/tblCheckpoint.sql
- dbo/Views/v_extract_recent_pom_org_data.sql
482414 - Master script
484992 - Restarting failure point in generate table from view procedure
> Changes for 2 tickets 482414 , 484992

- Database.sqlproj
- dbo/Stored Procedures/GenerateTableFromView.sql
- dbo/Tables/tblCheckpoint.sql
Changes for the ticket 484992 - Restart Reporting Pipeline from Failure point
> Changes for the ticket 484992 - Restart Reporting Pipeline from Failure point

- Database.sqlproj
- dbo/Views/v_CrossValidation_Landing_Page.sql
> 497856 Cross-validation-report-Landing Page

- Database.sqlproj
- dbo/Stored Procedures/sp_CrossValidation_pom_org_files.sql
- dbo/Views/v_CrossValidation_Landing_Page.sql
Following changes are included
Updated : dbo.v_CrossValidation_Landing_Page
Added : dbo.sp_CrossValidation_pom_org_files
> Cross validation SQL objects

- Database.sqlproj
- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails.sql
- dbo/Stored Procedures/sp_FilterAndPaginateOrganisationRegistrationSummaries.sql
- dbo/Stored Procedures/sp_OrganisationRegistrationSummaries.sql
- dbo/Views/v_ComplianceSchemeMembers.sql
- dbo/Views/v_OrganisationRegistrationSummaries.sql
- dbo/Views/v_PoM_Codes.sql
- dbo/Views/v_UploadedRegistrationDataBySubmissionPeriod.sql
producer journey and small producer changes
> producer journey and small producer changes

- Database.sqlproj
- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails.sql
- dbo/Stored Procedures/sp_FilterAndPaginateOrganisationRegistrationSummaries.sql
- dbo/Stored Procedures/sp_OrganisationRegistrationSummaries.sql
- dbo/Views/v_ComplianceSchemeMembers.sql
- dbo/Views/v_OrganisationRegistrationSummaries.sql
- dbo/Views/v_PoM_Codes.sql
- dbo/Views/v_UploadedRegistrationDataBySubmissionPeriod.sql
> producer journey and small producer changes (#150)

- dbo/Views/v_POM_All_Submissions.sql
added  company details to get subsidiary name, added new column
SQL view change for ticket 475754
> SQL view change for ticket 475754

- dbo/Stored Procedures/sp_compare_org_file.sql
- dbo/Tables/t_latest_accepted_orgfile_by_year.sql
- dbo/Tables/t_latest_pending_or_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
499950 - Joiners and Leavers report - Include additional details for Leavers for CS and Direct producers
> 499950 - Joiners and Leavers report - Include additional details for Leavers for CS and Direct producers

- dbo/Views/v_Large_Producers.sql
PLLP fix for tickets 501627, 501622
> PLLP fix for tickets 501627, 501622

- dbo/Stored Procedures/sp_GetProducerDetailsByOrganisationId.sql
- dbo/Views/v_PRN_Details.sql
- dbo/Views/v_PRN_Obligations.sql
- dbo/Views/v_registration_with_brandandpartner.sql
- dbo/Views/v_submitted_pom_org_file_status.sql
500555 - fix - Regulator journey bug fix for R7
> 500555 - fix - Regulator journey bug fix for R7

- dbo/Stored Procedures/sp_CrossValidation_pom_org_files.sql
500287 - Cross validation report - SQL - Include All Producers in the response
> Ticket - 500287

- dbo/Stored Procedures/sp_GetProducerDetailsByOrganisationId.sql
- dbo/Views/v_PRN_Details.sql
- dbo/Views/v_PRN_Obligations.sql
- dbo/Views/v_registration_with_brandandpartner.sql
- dbo/Views/v_submitted_pom_org_file_status.sql
501685, 501253,500601,500408, 500555 Rugulator journey bug fix for R7
> 501685, 501253,500601,500408, 500555 - fix (#160)

- dbo/Views/v_CrossValidation_Landing_Page.sql
Cross validation report - Landing Page - SQL 
Power Bi sort columns added
> Ticket - 485368

- dbo/Views/v_Registration_Comparison_Landing_Page.sql
Ticket - Registration comparison report  - The are duplicate instances of Direct producers displayed in the slicer
> Ticket - 498963

- dbo/Tables/t_registration_with_brandandpartner.sql
[dbo].[t_registration_with_brandandpartner] is added to project to remove the dependencies.
> Table added

- dbo/Views/v_Large_Producers.sql
- dbo/Views/v_extract_recent_pom_org_data.sql
PLLP changes for release 6.2 (#117)
> PLLP changes for release 6.2 (#117)

- dbo/Stored Procedures/GenerateTableFromView.sql
- dbo/Views/v_extract_recent_pom_org_data.sql
482414 - Master script
484992 - Restarting failure point in generate table from view procedure
4f37a553-on-r8.1
> Changes for 2 tickets (#146)-482414-484992 

- dbo/Stored Procedures/sp_GetProducerDetailsByOrganisationId.sql
500555 v2 sp_GetProducerDetailsByOrganisationId ISNULL added - missing in first cherry pick
> 500555 v2 sp_GetProducerDetailsByOrganisationId

- dbo/Views/v_Large_Producers.sql
PLLP fix for tickets 501627, 501622 (#159)
> PLLP fix for tickets 501627, 501622 (#159)

- dbo/Stored Procedures/sp_CrossValidation_pom_org_files.sql
- dbo/Views/v_CrossValidation_Landing_Page.sql
- Cross validation Report - Output Table Columns
> Ticket - 412814 

- dbo/Views/v_enrolment_report.sql
Date format has been modified.
> Feature/506875 V1

- dbo/Functions/udf_DQ_SubmissionPeriod.sql
500601 - function change to include Jul entry (#184)
> 500601 - function change to include Jul entry (#184)

- dbo/Stored Procedures/sp_CrossValidation_pom_org_files.sql
Updating AC-8 requirement accordingly
> Ticket - 412666-V2

- Database.sqlproj
- dbo/Tables/t_cosmos_file_metadata.sql
- dbo/Tables/t_registration_with_brandandpartner.sql
- dbo/Views/v_registration_with_brandandpartner.sql
- dbo/Views/v_submitted_pom_org_file_status.sql
Objects:
510914 506054 506055
v_registration_with_brandandpartner
v_submitted_pom_org_file_status
> Tickets 510914 506054 506055

- dbo/Views/v_New_Enrolment_Report.sql
Cherry pick from R9 to R8.1 for following tickets
462849
> 462849-additional columns (#127) (#128)

- dbo/Stored Procedures/GenerateTableFromView.sql
Cherry pick R9 to R8.1
For the ticket 484992
> 484992 (#168)

- Database.sqlproj
- Security/SqlAnalyticsConnector.sql
- dbo/Views/v_CrossValidation_Landing_Page.sql
Updated the relevant years in accordance with the latest requirements in the ticket:510249.
> 510249-update relevant years

- dbo/Stored Procedures/GenerateTableFromView.sql
GenerateTableFromView correction to match to R9 changes
> GenerateTableFromView correction to match to R9 changes

- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
Ticket 512853 JL new status
v_latest_pending_or_accepted_orgfile_by_year
v_latest_accepted_orgfile_by_year
> Ticket 512853 JL new status

- Database.sqlproj
- dbo/Views/v_get_orgfile_submitted_year_nation.sql
- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
Joiners and leavers report - nation column is added
> Ticket-514441 J&L

- dbo/Views/v_get_orgfile_submitted_year_nation.sql
> Ticket 5144441-V1

- dbo/Views/v_New_Enrolment_Report.sql
Enrolment Report decision date format
> Ticket - 462849 versioned

- Database.sqlproj
- dbo/Stored Procedures/sp_PRN_Delta_Extract.sql
- dbo/Views/v_UploadedRegistrationDataBySubmissionPeriod.sql
512517 & 512516 - Producer Journey team Bug fix to existing view Ticket number 
View updated: [dbo].[v_UploadedRegistrationDataBySubmissionPeriod]
513338 - PRN Delta SP - new Object to facilitate data extraction for API team.
> 512517 ,  512516, 513338  Checking in Producer team View and PRN Delta SP for R8.1

- Database.sqlproj
- dbo/Stored Procedures/sp_PRN_Delta_Extract.sql
- dbo/Views/v_UploadedRegistrationDataBySubmissionPeriod.sql
Cherry picking objects up into R9 from R8.1
sp_PRN_Delta_Extract (Sebastian)
&
v_UploadedRegistrationDataBySubmissionPeriod (front end team)
> Checking in Producer team View and PRN Delta SP for R8.1 (#206)

- dbo/Views/v_extract_recent_pom_org_data.sql
516110 - master script 2025 year changes
Object : [dbo].[v_extract_recent_pom_org_data]
> 516110 - master script 2025 year changes

- dbo/Stored Procedures/sp_compare_org_file.sql
- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
Ticket 515351
Objects :
view - dbo/Views/v_latest_accepted_orgfile_by_year.sql
view - dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
sp - dbo/Stored Procedures/sp_compare_org_file.sql
> 515351 JL - adding name and phone number 

- dbo/Tables/t_latest_accepted_orgfile_by_year.sql
- dbo/Tables/t_latest_pending_or_accepted_orgfile_by_year.sql
Ticket 515351
Objects
table - dbo.t_latest_accepted_orgfile_by_year
table - dbo.t_latest_pending_or_accepted_orgfile_by_year
> 515351 - t table changed to add columns

- dbo/Stored Procedures/sp_compare_org_file.sql
- dbo/Tables/t_latest_accepted_orgfile_by_year.sql
- dbo/Tables/t_latest_pending_or_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
Ticket : 515351
Desc : final and correct version of all objets
Objects:
view - dbo/Views/v_latest_accepted_orgfile_by_year.sql
view - dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
sp - dbo/Stored Procedures/sp_compare_org_file.sql
table - dbo.t_latest_accepted_orgfile_by_year
table - dbo.t_latest_pending_or_accepted_orgfile_by_year
> 515351_Joiners_and_Leavers_Report_V3

- dbo/Stored Procedures/sp_CrossValidation_pom_org_files.sql
Two filters are added to Org_Regulator_Status column and Pom_Regulator_Status to include rows only when Org_Regulator_Status and Pom_Regulator_Status have the following four values: pending, accepted, queried, granted.
> fix bugs for stored procedure

- dbo/Views/v_CrossValidation_Landing_Page.sql
pending, accepted, queried and granted are included
> update the landing page to include granted and queried

- dbo/Stored Procedures/sp_compare_org_file.sql
- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
Ticket : 510240
Object :
SP - [dbo].[sp_compare_org_file]
View - [dbo].[v_latest_accepted_orgfile_by_year]
View - [dbo].[v_latest_pending_or_accepted_orgfile_by_year]
> 510240 - JL - 2025 submission period changes

- dbo/Views/v_submitted_pom_org_file_status.sql
Defect 516110, 512853
To include new status as Uploaded
Object dbo.v_submitted_pom_org_file_status
> Defect 516110, 512853

- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails.sql
- dbo/Stored Procedures/sp_FilterAndPaginateOrganisationRegistrationSummaries.sql
Producer journey changes for R8.1
> PRoducer journey changes for R8.1

- dbo/Tables/t_latest_accepted_orgfile_by_year.sql
- dbo/Tables/t_latest_pending_or_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
Ticket 515349 
Report JL 
New columns leaver_code, leaver_date, Organisation_change_reason, joiner_date
> 515349 JL new columns

- dbo/Stored Procedures/sp_CrossValidation_pom_org_files.sql
there was a bug caused by being overwritten by old version of stored procedure. this bug is fixed.
> fix bug for cross-validation stored procedure

- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
- dbo/Tables/t_CompanyBrandPartnerFileUploadSet.sql
- dbo/Views/v_CompanyBrandPartnerFileUploadSet.sql
- rpd/Tables/CompanyDetails.sql
Registration comparison report - Organisation Size Changes to be included in Registration comparison report for comparison
> 473947 RCR org size

- dbo/Stored Procedures/sp_compare_org_file.sql
515349 
JL report
Object : [dbo].[sp_compare_org_file]
> 515349 JL - SP change

- dbo/Views/v_POM_All_Submissions.sql
- dbo/Views/v_POM_Submissions.sql
> Reverting long running views

- dbo/Views/v_POM_All_Submissions.sql
- dbo/Views/v_POM_Submissions.sql
> Reverting long running views (#230)

- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
- dbo/Tables/t_CompanyBrandPartnerFileUploadSet.sql
- dbo/Views/v_CompanyBrandPartnerFileUploadSet.sql
- rpd/Tables/CompanyDetails.sql
> Registration comparison report - Organisation Size (#227)

- dbo/Stored Procedures/sp_compare_org_file.sql
- dbo/Tables/t_latest_accepted_orgfile_by_year.sql
- dbo/Tables/t_latest_pending_or_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_accepted_orgfile_by_year.sql
- dbo/Views/v_latest_pending_or_accepted_orgfile_by_year.sql
ab13d33d-0f9bd76a-on-R9
Ticket 515349 JL ticket
cherry picked changes from R11 to R9
> Ab13d33d 0f9bd76a on r9

- dbo/Views/v_POM_All_Submissions.sql
This change is to remove join which is impacting the performance of the view
> REmoving the company details join which created performance impact

- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
- dbo/Tables/t_CompanyBrandPartnerFileUploadSet.sql
- dbo/Views/v_CompanyBrandPartnerFileUploadSet.sql
- rpd/Tables/CompanyDetails.sql
Reverts DEFRA/epr-data-sqldb#233
> Revert "Registration comparison report - Organisation Size (#227)"

- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
Organisation change reason added to comparison and as column.
> 513369-Organisation change reason added to comparison and as column.

- dbo/Views/v_CrossValidation_Landing_Page.sql
update landing page view code. the task number is 517048
> update crossvalidation landing page 517048

- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
Change of membership logic to be updated to include new leaver codes to identify the removed organisations for Compliance schemes
> 519044 - Change of membership logic

- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
remove org size column from R9
> remove org size column from R9

- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
Change of membership logic to be updated to include new leaver codes to identify the removed organisations for Compliance schemes
> ticket - 519044-V1

- dbo/Views/v_organisation_details_not_submitted.sql
fix v_organisation_details_not_submitted
> Ticket - 520218

- dbo/Stored Procedures/sp_FetchOrganisationRegistrationSubmissionDetails_resub.sql
- dbo/Stored Procedures/sp_OrganisationRegistrationSummaries_resub.sql
Front end R9 stored proc changes
> Front end R9 stored proc changes (#270)

- dbo/Stored Procedures/sp_CrossValidation_pom_org_files.sql
the bug is fixed by update Pom_data function in stored procedure
> fix bugs related to ticket 543006

- dbo/Views/v_submitted_pom_org_file_status.sql
543160 status fix [dbo].[v_submitted_pom_org_file_status]
> 543160 status view fix [dbo].[v_submitted_pom_org_file_status]

- dbo/Views/v_submitted_pom_org_file_status.sql
543160 created field fix
object [dbo].[v_submitted_pom_org_file_status]
> 543160 created fix

- Database.sqlproj
- dbo/Views/v_public_register_all_producers.sql
public register view changes for R11
> public register view changes for R11

- dbo/Views/v_extract_recent_pom_org_data.sql
515340
Master script to show POM data for rejected records
OBject : [dbo].[v_extract_recent_pom_org_data]
> Feature/515340 master script to show Submission data

- Database.sqlproj
- dbo/Stored Procedures/sp_delete_duplicate_rows.sql
546608-Improvement - Remove Duplicates from cosmos copy table
Object : dbo/Stored Procedures/sp_delete_duplicate_rows.sql
> 546608  Duplicate records removal

- dbo/Tables/t_BrndPrtnr_Registrations.sql
- dbo/Views/v_BrndPrtnr_Registrations.sql
550651
Adding registration ref number to registration report
dbo/Tables/t_BrndPrtnr_Registrations.sql
dbo/Views/v_BrndPrtnr_Registrations.sql
> 550651 registration ref num

- Delta Lake Files/PRN_ctrl_table.csv
Remove duplicate entries from control file.
> Correct PRN control file

- dbo/Views/v_extract_recent_pom_org_large_data.sql
515337
Object dbo/Views/v_extract_recent_pom_org_large_data.sql
MAster script changes to restrict columns in the large producer file output
> 515337 Master script v2

- dbo/Views/v_submitted_pom_org_file_status.sql
R9.0/R10.0 PRE - Cancellation of Registration showing against Registration Resubmission
> Ticket-561556

- dbo/Views/v_extract_recent_pom_org_data.sql
562429 
Master script single file submission flag
dbo/Views/v_extract_recent_pom_org_data.sql
> 562429 master script single file submission flag

- rpd/Tables/ComplianceSchemes.sql
- rpd/Tables/Organisations.sql
change in distribution and index for enrolment tables - 562567
> change in distruibution and index for enrolment tables - 562567

- Database.sqlproj
- dbo/Views/v_PayCal_Org.sql
- dbo/Views/v_PayCal_Pom.sql
Check in of PayCal Views v_PayCal_Org and _Pom.
Covers a large number of tickets developed over a number of months.
> 522656 and 510600 - latest tickets:

- dbo/Views/v_extract_recent_pom_org_data.sql
548936
Master script not to show resubmitted POM submission with "Uploaded" status
dbo/Views/v_extract_recent_pom_org_data.sql
> 548936 master script pom uploaded status

- dbo/Views/v_POM_Ram_Rag_Order.sql
Check in of updated version of v_POM_Ram_Rag_Order from a dynamic script relying on rpd.pom table to a static script since this is just a reference data table power bi uses to order data on a report.
> 566012 check in of updated v_POM_Ram_Rag_Order to static script version

- dbo/Views/v_submitted_pom_org_file_status.sql
548534_POM_resubmission_status
dbo/Views/v_submitted_pom_org_file_status.sql
> 548534_POM_resubmission_status

- dbo/Views/v_POM_All_Submissions.sql
569458 pom resubmission view fix
dbo/Views/v_POM_All_Submissions.sql
> 569927 POM resubmission date

- dbo/Views/v_reported_mandated_data_sets.sql
r13 master report year fix
dbo/Views/v_reported_mandated_data_sets.sql
> R13-master-reportyear-fix

- Database.sqlproj
- dbo/Views/v_Compliance_Report.sql
- dbo/Views/v_relevant_year_lookup.sql
Check in for Jacob of bug fix 578154 for Compliance Report not showing data.
> 578154-compliance-report-not-showing-data bug fix

- dbo/Tables/t_POM_Com_Landing_Filter.sql
- dbo/Tables/t_POM_Submissions_POM_Comparison.sql
- dbo/Views/v_POM_Com_Landing_Filter.sql
- dbo/Views/v_POM_Submissions_POM_Comparison.sql
POM resubmission  - Regulator status to be included in the POM comparison report and correct status displayed - SQL
> Feature/569458 POM COM regulator status

- dbo/Stored Procedures/GenerateTableFromView.sql
- dbo/Tables/t_rpd_data_SECURITY_FIX.sql
Performance Issue in Stored Procedure [dbo].[v_rpd_data_SECURITY_FIX] (Reporting Pipeline)
> Ticket-576271

- rpd/Tables/EnrolmentStatuses.sql
- rpd/Tables/InterOrganisationRoles.sql
- rpd/Tables/Nations.sql
- rpd/Tables/OrganisationRegistrationTypes.sql
- rpd/Tables/OrganisationRelationshipTypes.sql
- rpd/Tables/OrganisationToPersonRoles.sql
- rpd/Tables/OrganisationTypes.sql
- rpd/Tables/PersonInOrganisationRoles.sql
- rpd/Tables/ProducerTypes.sql
- rpd/Tables/ServiceRoles.sql
- rpd/Tables/Services.sql
Profile Account Database and Define Correct Data Types for Delta Lake and Synapse Tables - Part 2
> Ticket-570430

- dbo/Views/v_extract_recent_pom_org_data.sql
569433-master-script-orgsize-correction
dbo/Views/v_extract_recent_pom_org_data.sql
> 569433-master-script-orgsize-correction

- Database.sqlproj
- dbo/Views/v_RE_EX_enrolment_report.sql
Adding the new view for RE/EX to R13.2
> Added the new RE/EX view

- dbo/Stored Procedures/POM_Comparison_DRILL.sql
- dbo/Stored Procedures/POM_Comparison_members.sql
Subsidiary Retrofit column removal - POM comparison report
> Ticket - 576288

- dbo/Stored Procedures/Registration_Comparison_Change_Of_Member_and_Membership.sql
- dbo/Stored Procedures/sp_compare_org_file.sql
> 582538_changes

- dbo/Views/v_BrndPrtnr_Registrations.sql
- dbo/Views/v_Compliance_Report.sql
Updates for ComplianceReport and RegBrndPart to fix bugs from r13
> Updates for ComplianceReport and RegBrndPart to fix bugs from r13

- dbo/Views/v_BrndPrtnr_Registrations.sql
592335 remove duplicates from registration details
> 592335 Remvoe duplicates

- dbo/Views/v_Compliance_Report.sql
- dbo/Views/v_PRN_Obligations.sql
Adding nation to views for RLS in reports 567886 513680
> Adding nation to views for RLS in reports 567886 513680

- dbo/Views/v_POM_All_Submissions.sql
Packaging Supplied - 3 Reports - Update PoM submission application date and time handling in Power BI.
> Ticket - 603393

- dbo/Views/v_Compliance_Report.sql
compliance report reg submissions status bug fix 605827
> compliance report reg submissions status bug fix 605827

- dbo/Views/v_Large_Producers.sql
include_pending_status_in_PLLP_from_R14
> include_pending_status_in_PLLP_from_R14

- dbo/Views/v_public_register_all_producers.sql
The fix for the public register all producer
> Ticket - 611798

- dbo/Views/v_public_register_all_producers.sql
> Ticket 611798
